export enum AppErrorCode {
  BAD_REQUEST = "COMMON_BAD_REQUEST",
  VALIDATION_FAILED = "COMMON_VALIDATION_FAILED",
  UNAUTHORIZED = "COMMON_UNAUTHORIZED",
  FORBIDDEN = "COMMON_FORBIDDEN",
  NOT_FOUND = "COMMON_NOT_FOUND",
  INTERNAL_ERROR = "COMMON_INTERNAL_ERROR",
  EMAIL_ALREADY_EXISTS = "AUTH_EMAIL_ALREADY_EXISTS",
}
